# Data_Generation_Parameters.R

"
    How to set parameters:
    Parameters are supposed to be one of the following:
      1) A single value
      2) A vector of possible values
      3) A distribution of possible values
    
    Conditions:
      0) The name of the variable NEEDS to be 'Parameters'
      2) The vector should not be named
      3) If the data is supposed to follow a specific distribution, the syntax is:
          >argument <- list(func=randomdistribution_function,
                            c(name1=value1,
                              name2=value2,
                              name3=value3,
                              ...),
                            islog10=[FALSE]
                           )
         where randomdistribution_function is the function that generates random elements and the second
         argument is the named list with the variables that need to be passed to said function.
         example:
          > mpeak <- list(func=runif, c(min=0, max=1))
         The list or arguments is going to be passed on to the function, so the name of argumentX need
         to coincide with the inputs for the function.
         There is one exception, and that is the 'islog10' argument, which indicates if this follows the log
         distribution and as a final step x=10^argument.
      3b) The argument 'n' should NOT be given
      3c) A custom random distribution can be given. However, the first variable NEEDS to be 'n' and 
          be the number of answers generated by the function.
      4) If zfunc is not a function, it can be an integer or a non-integer. In that case, it will be considered
         constant and equal to the zfunc-th element in speclib$Z, or constant and equal to zfunc if an integer
         or non-integer respectively. For more information, look at documentation for SFHfunc>Arguments>Z.
    
    Additional Parameters:
      > RndSeed: Seed to be used for the random number generation.
                 If NULL is given, one will be generated.
      > massinburst: NULL, float in [0,1], or distribution.
                 If NULL, it will consider the rest of the burst-related parameters to NOT be NULL.
                 If float, it requieres that either mburstage=NULL and mburst=value or viceversa.
                 If distribution, it follows the same syntax as 3). This is useful if using Pessa et al. 2021.
                 massinburst represents the fraction (0-1) of mass that was generated during the burst.
      > div_massinburst_by_totalmass: [FALSE]
                 Optional parameter. If TRUE, massinburst will be divided by totalmass. This should be TRUE
                 when the massinburst ratio is given in absolute (e.g. when Pessa, or another distribution is
                 used, and the final massinburst depends on the totalmass parameter).
      > probburst:float in [0,1].
                 Probability of there being burst in the dataset.
      > totalmass: [NULL], values, or distribution
                 Total mass towards which the mass function will be resized.
      > z:       [1e-4]
                 Redshift. 'Indirectly', it gives us the distance.
      
    Some default configurations:
    Pessa et al. relation:
    {
      probburst=?,    # fraction of cases with burst
      mburstage=list(func=runif, c(min=0.005, max=0.1), islog10=FALSE),
      totalmass=list(func=rnorm, c(mean=8, sd=1), islog10=TRUE),
      massinburst=list(func=rnorm, c(mean=-3, sd=1), islog10=TRUE),
      div_massinburst_by_totalmass=TRUE,
      mburst=NULL
    }
    
    NOTE:
    As a reminder, it is easier to combine datasets than to make only one hyperspecific data generation.
    This is why we no longer consider implementing multiple massfunctions in a single data generation.
                 
"


# Parameters <- list(
#   RndSeed=NULL,
#   probburst=0.4,
#   div_massinburst_by_totalmass=FALSE,
#   totalmass=NULL,
#   
#   name="snorm_burst",
#   massfunc=massfunc_snorm_burst,
#   mSFR=10,
#   mpeak=seq(7,14.2,0.3),
#   mperiod=seq(0.5,1.5, 0.2),
#   mskew=seq(-0.5, 1, 0.1),
#   mburstage=0.1,
#   mburst=5,
#   massinburst=NULL,
#   
#   zfunc=Zfunc_massmap_box,
#   Zstart=1e-4,
#   yield=0.03,
#   Zfinal=seq(0.02, 0.08, 0.02)
# )

Parameters <- list(
  RndSeed=42,
  probburst=0.4,
  totalmass=list(func=rnorm, c(mean=8, sd=1), islog10=TRUE),
  div_massinburst_by_totalmass=TRUE,
  z=1e-4,
  
  name="snorm_burst",
  massfunc=massfunc_snorm_burst,
  mSFR=10,
  mpeak=list(func=rnorm, c(mu=11, sd=3)),
  mperiod=list(func=rnorm, c(mu=1, sd=0.4)),
  mskew=seq(-0.5, 1, 0.05),
  
  mburstage=list(func=runif, c(min=1e-3, max=0.1), islog10=FALSE),
  massinburst=list(func=rnorm, c(mean=-3, sd=1), islog10=TRUE),
  mburst=NULL,
  
  zfunc=Zfunc_massmap_box,
  Zstart=1e-4,
  yield=0.03,
  Zfinal=seq(0.02, 0.08, 0.02)
)