# Data_Generation_Parameters.R

"
    How to set parameters:
    Parameters are supposed to be one of the following:
      1) A single value
      2) A vector of possible values
      3) A distribution of possible values
    
    Conditions:
      0) The name of the variable NEEDS to be 'Parameters'
      2) The vector should not be named
      3) If the data is supposed to follow a specific distribution, the
         syntax is:
          >argument <- list(func=randomdistribution_function,
                            arg=c(name1=value1,
                                  name2=value2,
                                  name3=value3,
                                  ...),
                            [islog10=FALSE,]
                            [min_val=NULL,]
                            [max_val=NULL,]
                           )
         where randomdistribution_function is the function that generates
         random elements and the second argument is the named list with the
         variables that need to be passed to said function. For example:
          > mpeak <- list(func=runif, arg=c(min=0, max=1))
         The list or arguments is going to be passed on to the function, so the
         name of argumentX need to coincide with the inputs for the function.
      3b) There is are a few exceptions for possible additional arguments:
            > islog10: Used for defining cases where exponents are used. A
                       further step is going to be used where 'x = 10^value'
            > min_val/max_val: If a value is over/below these values, it will
                       overwrite it with the max/min value (e.g. usefull when
                       using rnorm for exclusively positive values [mburstage]).
      3c) The argument 'n' should NOT be given
      3d) A custom random distribution can be given. However, the first
          variable NEEDS to be 'n' and be the number of answers generated by
          the function.
      4) If zfunc is not a function, it can be an integer or a non-integer. In
         that case, it will be considered constant and equal to the 'zfunc-th'
         element in speclib$Z, or constant and equal to zfunc if an integer or
         non-integer respectively. For more information, look at documentation
         for SFHfunc>Arguments>Z.
    
    Additional Parameters:
      > RndSeed: Seed to be used for the random number generation.
                 If NULL is given, one will be generated.
      > SNR:     [0], numeric > 0
                 If SNR>0, it will add noise to the resulting spectra using
                 SNR as the Signal-Noise Ratio.
      > burstfraction: NULL, float in [0,1], or distribution.
                 -If NULL, it will consider the rest of the burst-related
                 parameters to NOT be NULL.
                 -If float, it requieres that mburst=NULL and mburstage=value.
                 -If distribution, it follows the same syntax as 3). This is
                 useful if using Pessa et al. 2021. massinburst represents the
                 fraction (0-1) of mass that was generated during the burst.
      > probburst: [1], float in [0,1].
                 Probability of there being burst in the dataset.
      > totalmass: [NULL], values, or distribution
                 Total mass towards which the mass function will be resized.
      > mSFR:    NULL, or value.
                 If NULL, it will be adjusted so that it fits the rest of
                 the data.
      > z:       [1e-4]
                 Redshift. 'Indirectly', it gives us the distance.
      > stellpop  # ToDo
      > speclib   # ToDo
                 
    Additional Parameters specifically for SFHfunc:
      > emission: [TRUE], logical
      > emission_scale: ['SFR'] or 'FUV'
      > forcemass will be evaluated with totalmass. This is slightly more
        intuitive for the definition of the Parameters. 
      > filters: ['HST'], 'all', or list with filter data.
      > if Z should be constant, define zfunc as the value (should be within
        the [0.0001, 0.0300] interval. Higher metallicity is not considered in
        EMILESCombined).
      
      > Any additional parameter that is going given that appears in SFHfunc's,
        massfunc's, or zfunc's formals will be passed onto SFHfunc
    
    Cases for parameters:
      > 0: probburst < 1, and no burst is triggered
                Description... ToDo
      > A: totalmass and mburst known; mSFR=burstfraction=NULL
                Description... ToDo
      > B: totalmass and burstfraction known; mSFR=mburst=NULL
                Description... ToDo
      > C: totalmass, mSFR and mburst known; burstfraction=NULL
                Description... ToDo
      > D: mSFR and mburst known; totalmass=burstfraction=NULL
                Description... ToDo
    
    Some default configurations:
    Pessa et al. relation:
    {
      probburst=?,    # fraction of cases with burst
      mburstage=list(func=runif, arg=c(min=0.005, max=0.1), islog10=FALSE),
      totalmass=list(func=rnorm, arg=c(mean=8, sd=1), islog10=TRUE),
      mburst=list(func=rnorm, arg=c(mean=-3, sd=1), islog10=TRUE),
      burstfraction=NULL
    }
    
    NOTE:
    As a reminder, it is easier to combine datasets than to make only one
    hyperspecific data generation. This is why the code no longer considers
    implementing multiple massfunctions in a single data generation.
                 
"


Parameters <- list(
  stellpop="EMILESRecortado",
  interpolate_waveout=FALSE,
  RndSeed=42,
  SNR=30,
  probburst=1,
  sparse=1,
  waveout=seq(4700, 6247.75, 1.25),
  totalmass=list(func=rnorm, arg=c(mean=8, sd=1), islog10=TRUE),
  z=1e-4,
  filters="HST",
  emission=TRUE,
  emission_scale="SFR",
  veldisp=40,
  
  name="snorm_burst",
  massfunc=massfunc_snorm_burst,
  mSFR=NULL,
  mpeak=list(func=rnorm, arg=c(mean=12, sd=3)),
  mperiod=list(func=rnorm, arg=c(mean=1, sd=0.4)),
  mskew=list(func=runif, arg=c(min=-0.5, max=1.5)),
  
  mburstage=list(func=runif, arg=c(min=0.030, max=0.100), islog10=FALSE),
  mburst=list(func=rnorm, arg=c(mean=-3, sd=1), islog10=TRUE),
  burstfraction=NULL,
  
  zfunc=Zfunc_massmap_box,
  Zstart=list(func=runif, arg=c(min=log10(0.004), max=log10(0.01)), islog10=TRUE),
  yield=0.03,
  Zfinal=list(func=runif, arg=c(min=0.01, max=0.03), islog10=FALSE)
)
