# Main code/file
# Light Output Generated by AstroNomical objects

"
  REMINDER FOR THE FUTURE:
  
  IF DEBUGGING IS GIVING OUT ERRORS (i.e. going to compiler::tryCmpFun), the 
  issue is because it is trying to debug the compiler (for a faster execution
  in the future). To fix this, the function needs to be 'precompiled':
    - set the working directory
    - Execute the source of LOGAN
    - Load libraries
    - COMMENT EVERY LIBRARY LINE OUT
    - Now it should work fine
  
"
setwd("/Users/enrique/Documents/GitHub/LOGAN-SFH")
source("LOGAN.R")
library(ProSpect)
library(ggplot2)



massParams1 = list(
  dtau=list(
    name="dtau",
    func=massfunc_dtau,
    mpeak=c(seq(1,12,1)),
    mtau=seq(1, 4, 0.2)
  )
)


# Equals to no burst when mburst=0
massParams2 = list(
  exp=list(
    name="exp",
    func=massfunc_exp_burst,
    mtau=c(8, 9),
    mburstage=seq(0.01, 0.2, 0.01),
    mburst=seq(1, 5, 1)
  )
)

# Equals to no burst when mburst=0
# Equals norm when skew=0
massParams3a = list(
  snorm=list(
    name="snorm",
    func=massfunc_snorm_burst,
    mskew=seq(-0.25, 0.25, 0.25),
    mperiod=seq(0.25, 1, 0.25),
    mpeak=seq(9, 12, 1),
    mburstage=seq(0.01, 0.09, 0.02),
    mburst=seq(1, 5, 1)
  )
)

massParams3b = list(
  snorm=list(
    name="snorm",
    func=massfunc_snorm_burst,
    mskew=seq(-0.25, 0.25, 0.25),
    mperiod=seq(0.25, 1, 0.25),
    mpeak=seq(5, 8, 1),
    mburstage=seq(0.01, 0.09, 0.02),
    mburst=seq(1, 5, 1)
  )
)



massParams4 = list(
  snorm=list(
    name="snorm",
    func=massfunc_snorm_burst,
    mskew=seq(-0.25, 0.25, 0.25),
    mperiod=seq(1.25, 2, 0.25),
    mpeak=seq(5, 12, 1),
    mburstage=seq(0.01, 0.09, 0.02),
    mburst=seq(1, 5, 1)
  )
)


# massParamsoriginal = list(
#   snorm=list(
#     name="snorm",
#     func=massfunc_snorm_burst,
#     mskew=seq(-0.75, 0.75, 0.25),
#     mperiod=seq(0.25, 2, 0.25),
#     mpeak=seq(5, 12, 1),
#     mburstage=seq(0.01, 0.2, 0.02),
#     mburst=seq(1, 5, 1)
#   )
# )

massParamLists = list(massParams1, massParams2, massParams3)

ZParams1 = list(
  func=Zfunc_massmap_box,
  Zstart=1e-4,
  yield=0.03,
  Zfinal=seq(0.01, 0.05, 0.01)
)

ZParams2 = list(
  func=Zfunc_massmap_box,
  Zstart=1e-4,
  yield=0.03,
  Zfinal=seq(0.06, 0.1, 0.01)
)


if (FALSE){
  magemax=13.8
  func_ = massfunc_snorm_burst
  func_ = massfunc_dtau
  # mburst = 0, mSFR = 10, mpeak = 10, mperiod = 1, 
  # mskew = 0.5, mburstage = 0.1, magemax = 13.8, mtrunc = 2
  ages = seq(1e6, 13.8e9, 1e6)
  y = func_(ages,
            mskew=-0.75,
            mperiod=3,
            mpeak=10,
            mburstage = 0.1,
            mburst = 0)
  plot(ages, y, type="l", xlab='Age/yr', ylab='SFR / Msol/yr')
}

################################################################################
############################   Parameters  #####################################
################################################################################


EMILESCombined = readRDS(file="EMILESData/EMILESCombined.rds")
listOfNames = c()


outputFolder = "/Volumes/Elements/Outputs"
absolutePath = TRUE
randomSamples = 5
verboseSteps = randomSamples + 1
filters = "default"
cleanOutputFolder = FALSE
singleOutput = TRUE
confirmation = TRUE


constantArguments = list(ZParams = ZParams1,
                         folderPath = outputFolder,
                         absolutePath = absolutePath,
                         randomSamples = randomSamples,
                         speclib = EMILESCombined,
                         confirmation = confirmation,
                         verbose=1,
                         verboseSteps=verboseSteps,
                         filters=filters,
                         cleanOutputFolder=cleanOutputFolder,
                         singleOutput=singleOutput)


################################################################################
################################################################################
################################################################################


for (i in 3:length(massParamLists)){
  out <- do.call(generateSpecFromParams, c(massParamLists[i], constantArguments))
  listOfNames = c(listOfNames, out$name)
  t = out$time
  save(t, file=file.path(outputFolder, paste0("time_", out$name, ".rda")))
  
}


lapply(listOfNames, write, file.path(outputFolder, "FileSufixes2.txt"), append=TRUE, ncolumns=10000)



# 
# out <- generateSpecFromParams(massParams = massParams2,
#                               ZParams = ZParams,
#                               folderPath = outputFolder,
#                               absolutePath = absolutePath,
#                               randomSamples = randomSamples,
#                               speclib = EMILESCombined,
#                               confirmation = confirmation,
#                               verbose=1,
#                               verboseSteps=verboseSteps,
#                               filters=filters,
#                               cleanOutputFolder=cleanOutputFolder,
#                               singleOutput=singleOutput)
